"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# ✅ CORRETO: _file_ (dois underlines antes e depois)
BASE_DIR = Path(__file__).resolve().parent.parent


# ⚠ ATENÇÃO: em produção troque essa chave e use variável de ambiente
SECRET_KEY = 'django-insecure-np$sukkvjsg*qw15t3vt&borvm7f9ij709=bu#y(x91&fu9cur'

# Durante o desenvolvimento pode ficar True
DEBUG = True

# Em desenvolvimento vamos liberar tudo. Em produção, restrinja!
ALLOWED_HOSTS = ['*']


# Application definition
# -------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps de terceiros
    'rest_framework',
    'corsheaders',

    # Seu app
    'api_rest',
]

MIDDLEWARE = [
    # ✅ CORS sempre antes de CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# -------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# -------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# -------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# -------------------------------------------------------------------

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================
# ⚙ CONFIG CORS / CSRF
# ==========================

# 🔥 Desenvolvimento: libera todas as origens
# (quando for pra produção, é melhor trocar por CORS_ALLOWED_ORIGINS)
CORS_ALLOW_ALL_ORIGINS = True

# Se quiser restringir no futuro, comente a linha acima e use:
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:8100',
#     'http://127.0.0.1:8100',
#     'http://192.168.1.13:8100',  # Ionic na rede local
# ]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CSRF – origens confiáveis (para formulários, se usar)
CSRF_TRUSTED_ORIGINS = [
    'https://strangulable-masochistically-edyth.ngrok-free.dev',
    'http://localhost:4200',
    'http://127.0.0.1:4200',
    'http://localhost:8100',
    'http://127.0.0.1:8100',
    'http://10.9.131.164:8100/',  # 👈 seu IP com a porta do Ionic
]