# Generated by Django 5.2.8 on 2025-11-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_nickname', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('user_email', models.CharField(default='')),
                ('user_age', models.IntegerField(default=0)),
            ],
        ),
    ]
