# Generated by Django 5.2.8 on 2025-12-07 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('customer_cpf', models.CharField(max_length=11, unique=True)),
                ('customer_gender', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(max_length=50, unique=True)),
                ('customer_password', models.CharField(max_length=128)),
                ('customer_phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('professional_cpf', models.CharField(max_length=11, unique=True)),
                ('professional_gender', models.CharField(blank=True, max_length=20)),
                ('professional_email', models.EmailField(max_length=50, unique=True)),
                ('professional_password', models.CharField(max_length=128)),
                ('professional_phone', models.CharField(max_length=11)),
                ('crp', models.CharField(max_length=7)),
                ('specialty', models.CharField(blank=True, max_length=50)),
                ('abordagem', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Ativo', max_length=50)),
                ('inicio_terapia', models.DateField(blank=True, null=True)),
                ('anotacoes', models.TextField(blank=True, default='')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='api_rest.customer')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='api_rest.professional')),
            ],
        ),
    ]
