# Generated by Django 5.2.8 on 2025-12-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='profissional',
        ),
        migrations.AddField(
            model_name='prontuario',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='status',
            field=models.CharField(blank=True, default='Ativo', max_length=50),
        ),
    ]
