# Generated by Django 5.2.8 on 2025-11-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_usertask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
