# Generated by Django 5.2.8 on 2025-11-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_delete_usertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
