# Generated by Django 5.2.8 on 2025-11-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_alter_user_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(default='', max_length=100)),
                ('customer_cpf', models.CharField(default='', max_length=11, primary_key=True, serialize=False)),
                ('customer_gender', models.CharField(default='', max_length=20)),
                ('customer_email', models.CharField(default='', max_length=50)),
                ('customer_password', models.CharField(default='', max_length=12)),
                ('customer_phone', models.CharField(default='', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('professional_cpf', models.CharField(default='', max_length=11)),
                ('professional_gender', models.CharField(default='', max_length=20)),
                ('professional_email', models.CharField(default='', max_length=50)),
                ('professional_password', models.CharField(default='', max_length=12)),
                ('professional_phone', models.CharField(default='', max_length=11)),
                ('crp', models.CharField(default='', max_length=7)),
                ('specialty', models.CharField(blank=True, default='', max_length=50)),
                ('abordagem', models.CharField(default='', max_length=20)),
                ('descricao', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
