# Generated by Django 5.2.8 on 2025-11-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_customer_professional_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='professional',
            name='professional_password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
