# Generated by Django 5.2.8 on 2025-12-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_alter_customer_customer_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('cpf', models.CharField(default='', max_length=14)),
                ('status', models.CharField(default='Ativo', max_length=50)),
                ('inicio_terapia', models.DateField(blank=True, null=True)),
                ('anotacoes', models.CharField(blank=True, default='')),
            ],
        ),
    ]
